spring:
  datasource:
    url: jdbc:mariadb://firstclass.c8rkj0sdknw8.ap-southeast-2.rds.amazonaws.com:3306/billim
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: first1234
  jpa:
    databaseplatform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: sfIehYeCDySiinRyGsqr
            client-secret: BwCl6Ab6IY
            redirect-uri: http://localhost:8080/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html

# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
